"""Initial commit

Revision ID: 245d87445e12
Revises: 
Create Date: 2021-07-05 20:45:40.831885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245d87445e12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grids_id'), 'grids', ['id'], unique=False)
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('grid_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grid_id'], ['grids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildings_id'), 'buildings', ['id'], unique=False)
    op.create_index(op.f('ix_buildings_name'), 'buildings', ['name'], unique=False)
    op.create_table('energytransactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('grid_timestamp', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energytransactions_id'), 'energytransactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_energytransactions_id'), table_name='energytransactions')
    op.drop_table('energytransactions')
    op.drop_index(op.f('ix_buildings_name'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_id'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_grids_id'), table_name='grids')
    op.drop_table('grids')
    # ### end Alembic commands ###
