"""2

Revision ID: 3be05348d9f5
Revises: de741f234fb1
Create Date: 2021-06-02 17:31:00.386725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3be05348d9f5'
down_revision = 'de741f234fb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('grid_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grid_id'], ['grid.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_building_id'), 'building', ['id'], unique=False)
    op.create_index(op.f('ix_building_name'), 'building', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_building_name'), table_name='building')
    op.drop_index(op.f('ix_building_id'), table_name='building')
    op.drop_table('building')
    # ### end Alembic commands ###
