"""4

Revision ID: 9e419badacd8
Revises: f8ede628b0a1
Create Date: 2021-06-02 17:39:56.083929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e419badacd8'
down_revision = 'f8ede628b0a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
