"""Default time is the current hour

Revision ID: a2e071bf506b
Revises: e1ff4ed31c4c
Create Date: 2021-07-03 17:56:06.326890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2e071bf506b'
down_revision = 'e1ff4ed31c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_energytransaction_id', table_name='energytransaction')
    op.drop_table('energytransaction')
    op.drop_index('ix_grid_id', table_name='grid')
    op.drop_table('grid')
    op.drop_index('ix_building_id', table_name='building')
    op.drop_index('ix_building_name', table_name='building')
    op.drop_table('building')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('direction', sa.VARCHAR(), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('grid_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['grid_id'], ['grid.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_building_name', 'building', ['name'], unique=False)
    op.create_index('ix_building_id', 'building', ['id'], unique=False)
    op.create_table('grid',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_grid_id', 'grid', ['id'], unique=False)
    op.create_table('energytransaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=True),
    sa.Column('receiver_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['building.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['building.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_energytransaction_id', 'energytransaction', ['id'], unique=False)
    # ### end Alembic commands ###
