"""5

Revision ID: e1ff4ed31c4c
Revises: 9e419badacd8
Create Date: 2021-06-02 17:49:59.597954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ff4ed31c4c'
down_revision = '9e419badacd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grids_id'), 'grids', ['id'], unique=False)
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('grid_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grid_id'], ['grids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildings_id'), 'buildings', ['id'], unique=False)
    op.create_index(op.f('ix_buildings_name'), 'buildings', ['name'], unique=False)
    op.create_table('energytransactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energytransactions_id'), 'energytransactions', ['id'], unique=False)
    op.drop_index('ix_building_id', table_name='building')
    op.drop_index('ix_building_name', table_name='building')
    op.drop_table('building')
    op.drop_index('ix_energytransaction_id', table_name='energytransaction')
    op.drop_table('energytransaction')
    op.drop_index('ix_grid_id', table_name='grid')
    op.drop_table('grid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grid',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_grid_id', 'grid', ['id'], unique=False)
    op.create_table('energytransaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=True),
    sa.Column('receiver_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['building.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['building.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_energytransaction_id', 'energytransaction', ['id'], unique=False)
    op.create_table('building',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('direction', sa.VARCHAR(), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('grid_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['grid_id'], ['grid.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_building_name', 'building', ['name'], unique=False)
    op.create_index('ix_building_id', 'building', ['id'], unique=False)
    op.drop_index(op.f('ix_energytransactions_id'), table_name='energytransactions')
    op.drop_table('energytransactions')
    op.drop_index(op.f('ix_buildings_name'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_id'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_grids_id'), table_name='grids')
    op.drop_table('grids')
    # ### end Alembic commands ###
