// BUILDING TYPES

export const UPDATE_BUILDING_TYPE = "UPDATE_BUILDING_TYPE";
export const UPDATE_BUILDING_ADDRESS = "UPDATE_BUILDING_ADDRESS";
export const UPDATE_BUILDING_CONSUMPTION = "UPDATE_BUILDING_CONSUMPTION";
export const UPDATE_BUILDING_MAX_PANELS = "UPDATE_BUILDING_MAX_PANELS";
export const UPDATE_BUILDING_PANELS = "UPDATE_BUILDING_PANELS";

export const ADD_BUILDING = "ADD_BUILDING";
export const REMOVE_BUILDING = "REMOVE_BUILDING";
export const ADD_TRANSACTION = "ADD_TRANSACTION";


// GRID TYPES

export const ADD_GRID = "ADD_GRID";